# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CANDIDAT: ROLE_CANDIDAT
        ROLE_SOCIETE: ROLE_SOCIETE
        ROLE_DGPE: ROLE_DGPE
        ROLE_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    access_denied_url: /login

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                #pour appeler une autre service apres authentification
                success_handler: redirect.after.login
                use_referer: true
            logout:
                path: /logout
                target: /
                success_handler: redirect.after.logout
                invalidate_session: true        
            
            anonymous:    true
        signup:
            pattern:  ^/register/signup
            anonymous: true

    access_control:        
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/offre/list, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_CANDIDAT,ROLE_SOCIETE,ROLE_DGPE,ROLE_ADMIN] }
