<?php

namespace RecruitmentBundle\Repository;

/**
 * DomaineUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineUserRepository extends \Doctrine\ORM\EntityRepository
{
}
