<?php

namespace RecruitmentBundle\Repository;

/**
 * RegleUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegleUserRepository extends \Doctrine\ORM\EntityRepository
{
}
