<?php

namespace RecruitmentBundle\Repository;

/**
 * RemovedOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemovedOffreRepository extends \Doctrine\ORM\EntityRepository
{
}
