<?php

namespace RecruitmentBundle\Repository;

/**
 * SocieteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocieteUserRepository extends \Doctrine\ORM\EntityRepository
{
}
