<?php

namespace UserBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

	public function getDiscussion($sender_id,$receiver_id)
	{
	    $qb = $this->createQueryBuilder('m')	    
	        ->where('( m.sender = :sender AND m.receiver = :receiver ) OR ( m.receiver = :sender AND m.sender = :receiver ) ')
	        ->orderBy('m.dateEnvoi','DESC')
	        ->setMaxResults(20)
	        ->setParameters(array('sender'=>$sender_id,'receiver'=>$receiver_id));

	    $results = $qb->getQuery()->getResult();
	    return array_reverse($results);
	}
}